[package]
name        = "snd"
version     = "0.0.0"
authors     = ["Casey Rodarmor <casey@rodarmor.com>"]
license     = "CC0-1.0"
homepage    = "https://github.com/casey/just"
description = "A polyphonic synthesizer"

[dependencies]
cpal      = "0.8.1"
float-cmp = "0.4.0"
rand      = "0.4.2"
